FROM debian:11.1

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  python3-pymongo \
  && rm -rf /var/apt/lists/*

COPY model /model

RUN pip3 install /model && rm -rf /model

COPY app /app

RUN pip3 install /app && rm -rf /app

CMD ["python3", "-m", "dogsearch.worker"]
