version: '3.8'
services:
  backend_db:
    build: ./backend/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME} 
    command: --replSet rs
    volumes:
      - backend_data:/data/db
    container_name: ${COMPOSE_PROJECT_NAME}_backend_db
  backend_api:
    build:
      context: ./backend/api
    depends_on:
      - backend_db
    environment:
      - DB_HOST=backend_db
      - DB_NAME
    container_name: ${COMPOSE_PROJECT_NAME}_backend_api
  backend_worker:
    build:
      context: ./backend/worker
    depends_on:
      - backend_db
    environment:
      - DB_HOST=backend_db
      - DB_NAME
      - MODEL_TYPE
  frontend:
    build: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
  proxy:
    build: ./proxy
    ports:
      - ${PORT}:80
    depends_on:
      - backend_api
      - frontend
    container_name: ${COMPOSE_PROJECT_NAME}_backend_proxy
volumes:
  backend_data: {}
