version: '3.8'
services:
  backend_api:
    volumes:
      - ./backend/api:/app
  backend_worker:
    volumes:
      - ./backend/worker/app:/app
      - ./backend/worker/model/code/dogsearch/model:/app/dogsearch/model
  frontend:
    environment:
      - REACT_APP_BASE_PATH=${BASE_PATH}
    volumes:
      - ./frontend:/app
      - /app/node_modules
