FROM node AS build

ARG REACT_APP_BASE_URL
ARG REACT_APP_BASE_PATH

COPY . app

WORKDIR /app

RUN yarn install --network-timeout 1000000 --frozen-lockfile

ENV PUBLIC_URL=${REACT_APP_BASE_URL}/${REACT_APP_BASE_PATH}
ENV REACT_APP_BASE_PATH=${REACT_APP_BASE_PATH}
ENV REACT_APP_AUTH_URL=${REACT_APP_AUTH_URL}
RUN yarn build

FROM nginx:1.19

COPY --from=build /app/build /var/www
COPY nginx.conf /etc/nginx/conf.d/default.conf
