FROM debian:11.1

RUN apt-get update && apt-get install -y \
  python3 \
  python3-pip \
  python3-pymongo \
  gunicorn3 \
  && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip3 install /app && rm -rf /app

CMD ["gunicorn3", "-b", "0.0.0.0:80", "dogsearch.api:app"]
